# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/causal-interpretability-agent',
                'doc_host': 'https://danaderp.github.io',
                'git_url': 'https://github.com/danaderp/causal-interpretability-agent',
                'lib_path': 'causal_interpretability_agent'},
  'syms': { 'causal_interpretability_agent.core': { 'causal_interpretability_agent.core.foo': ( 'core.html#foo',
                                                                                                'causal_interpretability_agent/core.py')}}}
